### ISSUE TITLE
Updating Twitter Logo

### ISSUE THREAD

**Issue by syrnxalno** [pooranjoyb/popShop#22] opened 2024-05-11 14:12 UTC

**Comment by pooranjoyb** [comment] 2024-05-11 21:32
Go for it! In fact can you do one thing? Replace all the SVGs in Footer with `react-icons` :))) 
@syrnxalno

**Comment by syrnxalno** [comment] 2024-05-12 04:03
Sure @pooranjoyb, I'll give it a go.

**Comment by syrnxalno** [comment] 2024-05-12 07:58
Hello admin @pooranjoyb , I'm finding it a little bit difficult to convert all of the SVGs in the footer into react-icons so is it alright if I just modify the twitter logo as per my initial suggestion?
Thank you for considering.

**Comment by pooranjoyb** [comment] 2024-05-12 09:19
Convert nahi karna hai, just remove the SVGs and uske jagah pe add the `react-icons` ka icons, check the official docs like how to use them. If you face any issues, you can DM @Mahitej28 or me in discord.

**Comment by sachin0986** [comment] 2024-05-12 10:11
Hi **@pooranjoyb** if you want, you can assign it to me, I have relevant skills to solve this.

**Comment by pooranjoyb** [comment] 2024-05-12 10:19
> Hi **@pooranjoyb** if you want, you can assign it to me, I have relevant skills to solve this.

Wait till EOD @sachin0986 , you will be assigned if no PR is raised by then. Let's keep the collaboration & contribution as priority and not as a competition! Hehehe :)

**Comment by Mahitej28** [comment] 2024-05-12 10:33
@syrnxalno let me know if u need any help

**Comment by Mahitej28** [comment] 2024-05-12 16:09
@sachin0986 the issue is now being assigned to you, you can work on it.
Make a pr to dev, also make sure to add react-ions in place of svg.

**Closed** 2024-05-12 18:33 UTC
Labels: ui, level1, gssoc
